#!/usr/bin/env python3
"""
Plot GELU ULP (Units in Last Place) error data from diagnostic test.

Usage:
    python3 plot_gelu_ulp.py [--suffix SUFFIX]

Input:  /tmp/gelu_ulp_data.csv (generated by GELU_ULP_DiagnosticDataCollection test)
Output: gelu_ulp_plot_<SUFFIX>.png (in same directory as this script)

Example:
    # Run the diagnostic test first
    ./ttml_tests --gtest_filter='*DISABLED_GELU_ULP_DiagnosticDataCollection*' --gtest_also_run_disabled_tests

    # Then generate the plot
    python3 plot_gelu_ulp.py --suffix wh_n150
"""

import argparse
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
from math import erf


def main():
    parser = argparse.ArgumentParser(description="Plot GELU ULP error data")
    parser.add_argument(
        "--suffix",
        default="",
        help="Hardware suffix for output filename (e.g., wh_n150)",
    )
    parser.add_argument(
        "--input", default="/tmp/gelu_ulp_data.csv", help="Input CSV file path"
    )
    args = parser.parse_args()

    # Read data
    csv_path = args.input
    if not os.path.exists(csv_path):
        print(f"Error: {csv_path} not found.")
        print("Run the diagnostic test first:")
        print(
            "  ./ttml_tests --gtest_filter='*DISABLED_GELU_ULP_DiagnosticDataCollection*' --gtest_also_run_disabled_tests"
        )
        return 1

    print(f"Reading {csv_path}...")
    df = pd.read_csv(csv_path)
    print(f"Loaded {len(df)} data points")

    # Create figure with multiple subplots
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.suptitle(
        "GELU Hardware Implementation: ULP Error Analysis (BFloat16)",
        fontsize=14,
        fontweight="bold",
    )

    # Plot 1: ULP vs Input Value (ALL bf16 values, symmetric log scale)
    ax1 = axes[0, 0]
    ax1.scatter(
        df["input_value"],
        df["ulp"],
        c="blue",
        s=1,
        alpha=0.3,
    )
    ax1.set_xlabel("Input Value (symlog scale)")
    ax1.set_ylabel("ULP Error (log scale)")
    ax1.set_title("ULP Error vs Input Value (Full BF16 Range)")
    # Use symmetric log scale for x-axis to handle large positive/negative values
    ax1.set_xscale("symlog", linthresh=1.0)
    # Use log scale for y-axis to show full ULP range (add 1 to handle ULP=0)
    ax1.set_yscale("symlog", linthresh=1.0)
    ax1.axhline(y=1, color="orange", linestyle="--", alpha=0.7, label="ULP=1")
    ax1.axhline(y=2, color="red", linestyle="--", alpha=0.7, label="ULP=2")
    ax1.axhline(y=128, color="purple", linestyle=":", alpha=0.7, label="ULP=128")
    ax1.legend(loc="upper right", fontsize=8)

    # Plot 2: ULP Distribution (histogram)
    ax2 = axes[0, 1]
    max_ulp_to_show = min(10, df["ulp"].max())
    ulp_counts = df["ulp"].value_counts().sort_index()
    ulp_range = range(int(max_ulp_to_show) + 1)
    counts = [ulp_counts.get(i, 0) for i in ulp_range]
    colors = [
        "green" if i == 0 else "yellow" if i == 1 else "orange" if i == 2 else "red"
        for i in ulp_range
    ]
    bars = ax2.bar(ulp_range, counts, color=colors, edgecolor="black", alpha=0.8)
    ax2.set_xlabel("ULP Error")
    ax2.set_ylabel("Count")
    ax2.set_title("ULP Error Distribution")
    ax2.set_xticks(list(ulp_range))

    # Add percentage labels on bars
    total = len(df)
    for bar, count in zip(bars, counts):
        if count > 0:
            pct = 100 * count / total
            ax2.text(
                bar.get_x() + bar.get_width() / 2,
                bar.get_height() + total * 0.01,
                f"{pct:.1f}%",
                ha="center",
                va="bottom",
                fontsize=8,
            )

    # Plot 3: Computed vs Expected (scatter, zoomed to interesting region)
    ax3 = axes[1, 0]
    # Focus on region where GELU has most variation: [-3, 3]
    mask = (df["input_value"] >= -3) & (df["input_value"] <= 3)
    df_zoom = df[mask]
    ax3.scatter(
        df_zoom["expected_bf16"],
        df_zoom["computed"],
        c=df_zoom["ulp"],
        cmap="RdYlGn_r",
        s=2,
        alpha=0.5,
        vmin=0,
        vmax=max(3, df_zoom["ulp"].max()),
    )

    # Perfect line
    lims = [df_zoom["expected_bf16"].min(), df_zoom["expected_bf16"].max()]
    ax3.plot(lims, lims, "k--", alpha=0.5, label="Perfect match")
    ax3.set_xlabel("Expected (bf16 quantized)")
    ax3.set_ylabel("Computed (hardware)")
    ax3.set_title("Computed vs Expected (input in [-3, 3])")
    ax3.legend()
    ax3.set_aspect("equal", adjustable="box")

    # Plot 4: ULP vs Input Value (zoomed to GELU active region)
    ax4 = axes[1, 1]
    # GELU has most variation in [-2, 2], with the "bump" around -1
    mask2 = (df["input_value"] >= -2) & (df["input_value"] <= 2)
    df_active = df[mask2]
    ax4.scatter(
        df_active["input_value"],
        df_active["ulp"],
        c=df_active["ulp"],
        cmap="RdYlGn_r",
        s=3,
        alpha=0.6,
        vmin=0,
        vmax=max(3, df_active["ulp"].max()),
    )
    ax4.set_xlabel("Input Value")
    ax4.set_ylabel("ULP Error")
    ax4.set_title("ULP Error in GELU Active Region [-2, 2]")
    ax4.axhline(y=1, color="orange", linestyle="--", alpha=0.7)
    ax4.axhline(y=2, color="red", linestyle="--", alpha=0.7)
    ax4.set_ylim(-0.5, min(5, df_active["ulp"].max() + 1))

    # Add GELU curve overlay (scaled)
    x_gelu = np.linspace(-2, 2, 200)
    y_gelu = 0.5 * x_gelu * (1 + np.vectorize(erf)(x_gelu / np.sqrt(2)))
    ax4_twin = ax4.twinx()
    ax4_twin.plot(x_gelu, y_gelu, "b-", alpha=0.3, linewidth=2, label="GELU(x)")
    ax4_twin.set_ylabel("GELU(x)", color="blue")
    ax4_twin.tick_params(axis="y", labelcolor="blue")

    plt.tight_layout()

    # Save plot (in same directory as script)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    suffix = f"_{args.suffix}" if args.suffix else ""
    output_path = os.path.join(script_dir, f"gelu_ulp_plot{suffix}.png")
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    print(f"\nPlot saved to: {output_path}")

    # Print summary statistics
    print("\n=== Summary Statistics ===")
    print(f"Total data points: {len(df)}")
    print(f"Max ULP: {df['ulp'].max()}")
    print(f"Mean ULP: {df['ulp'].mean():.4f}")
    print(f"Median ULP: {df['ulp'].median():.1f}")
    print(f"\nULP Distribution:")
    for ulp_val in range(min(5, df["ulp"].max() + 1)):
        count = (df["ulp"] == ulp_val).sum()
        pct = 100 * count / len(df)
        print(f"  ULP={ulp_val}: {count} ({pct:.2f}%)")
    ulp_gt4 = (df["ulp"] > 4).sum()
    if ulp_gt4 > 0:
        print(f"  ULP>4: {ulp_gt4} ({100*ulp_gt4/len(df):.2f}%)")

    # Show worst cases
    print("\n=== Worst Cases (highest ULP) ===")
    worst = df.nlargest(5, "ulp")[
        ["input_value", "computed", "expected_bf16", "ulp", "abs_diff"]
    ]
    print(worst.to_string(index=False))

    # Show the plot
    print(f"\nTo view: xdg-open {output_path}")
    plt.show()

    return 0


if __name__ == "__main__":
    exit(main())
